package frames;

import client.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Lucas Penha de Moura - 1208977
 */
public class clientInfos extends javax.swing.JFrame {

    private Client cli;
    //Mensagens
    private String M1;
    private String M2;
    private String M2_Pt1;
    private String M2_Pt2;
    private String M3;
    private String M4;
    private String M5;
    private String M6;
    private String splitM2[];
    private String splitM4[];

    //Chaves
    private String K_C_TGS;

    public clientInfos() {
        initComponents();
    }

    public clientInfos(Client cli) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cli = cli;
        tgsMsg_button.setEnabled(false);
        serverMsg_button.setEnabled(false);
        System.out.println("Cliente: " + cli.getID_C());
        System.out.println("Serviço: " + cli.getID_S());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        asMsg_button = new javax.swing.JButton();
        respASPT1_txt = new javax.swing.JTextField();
        tgsMsg_button = new javax.swing.JButton();
        M3_txt = new javax.swing.JTextField();
        serverMsg_button = new javax.swing.JButton();
        M5_txt = new javax.swing.JTextField();
        exit_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        respASPT2_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        M1_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        respTGSPT1_txt = new javax.swing.JTextField();
        respTGSPT2_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        M6_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        asMsg_button.setText("Mensagem Para AS");
        asMsg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asMsg_buttonActionPerformed(evt);
            }
        });

        respASPT1_txt.setEditable(false);

        tgsMsg_button.setText("Mensagem Para TGS");
        tgsMsg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgsMsg_buttonActionPerformed(evt);
            }
        });

        M3_txt.setEditable(false);

        serverMsg_button.setText("Mensagem Para Server");
        serverMsg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverMsg_buttonActionPerformed(evt);
            }
        });

        M5_txt.setEditable(false);
        M5_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M5_txtActionPerformed(evt);
            }
        });

        exit_button.setText("Sair");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("M2.1");

        jLabel5.setText("M2.2");

        respASPT2_txt.setEditable(false);

        jLabel6.setText("M1:");

        M1_txt.setEditable(false);

        jLabel7.setText("M3:");

        jLabel8.setText("M4.1");

        jLabel9.setText("M4.2");

        respTGSPT1_txt.setEditable(false);

        respTGSPT2_txt.setEditable(false);

        jLabel10.setText("M5:");

        jLabel1.setText("M6:");

        M6_txt.setEditable(false);

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 760, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respASPT2_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respASPT1_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M1_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M3_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respTGSPT1_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respTGSPT2_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M5_txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asMsg_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgsMsg_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serverMsg_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M6_txt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asMsg_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(M1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respASPT1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respASPT2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tgsMsg_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(respTGSPT1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respTGSPT2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(serverMsg_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(M6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_button)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asMsg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asMsg_buttonActionPerformed
        try {
            M1 = cli.messageGen("M1");
            M1_txt.setText(M1);//envia M1

            M2 = cli.ASConnecion(M1);//msg ja volta descriptografada

            splitM2 = M2.split(";");

            respASPT1_txt.setText(splitM2[0] + " -----> " + splitM2[1]);
            respASPT2_txt.setText(splitM2[2]);

            asMsg_button.setEnabled(false);
            tgsMsg_button.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(clientInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asMsg_buttonActionPerformed

    private void M5_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M5_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M5_txtActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void tgsMsg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgsMsg_buttonActionPerformed
        try {
            M3 = cli.messageGen("M3");
            M3_txt.setText(M3);

            M4 = cli.TGSConnection(M3);
            splitM4 = M4.split(";");

            respTGSPT1_txt.setText(splitM4[0] + " -----> " + splitM4[1]);
            respTGSPT2_txt.setText(splitM4[2]);

            tgsMsg_button.setEnabled(false);
            serverMsg_button.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(clientInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tgsMsg_buttonActionPerformed

    private void serverMsg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverMsg_buttonActionPerformed
        try {
            M5 = cli.messageGen("M5");
            M5_txt.setText(M5);

            M6 = cli.ServerConnection(M5);
            M6_txt.setText(M6);

            serverMsg_button.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(clientInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_serverMsg_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //parte 1 --> M1 e M2
            M1 = cli.messageGen("M1");
            M1_txt.setText(M1);//envia M1

            M2 = cli.ASConnecion(M1);//msg ja volta descriptografada

            splitM2 = M2.split(";");

            respASPT1_txt.setText(splitM2[0] + " -----> " + splitM2[1]);
            respASPT2_txt.setText(splitM2[2]);

            //parte 2 --> M3 e M4
            M3 = cli.messageGen("M3");
            M3_txt.setText(M3);

            M4 = cli.TGSConnection(M3);
            splitM4 = M4.split(";");

            respTGSPT1_txt.setText(splitM4[0] + " -----> " + splitM4[1]);
            respTGSPT2_txt.setText(splitM4[2]);

            //parte 3 --> M5 e M6
            M5 = cli.messageGen("M5");
            M5_txt.setText(M5);

            M6 = cli.ServerConnection(M5);
            M6_txt.setText(M6);

        } catch (IOException ex) {
            Logger.getLogger(clientInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientInfos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M1_txt;
    private javax.swing.JTextField M3_txt;
    private javax.swing.JTextField M5_txt;
    private javax.swing.JTextField M6_txt;
    private javax.swing.JButton asMsg_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField respASPT1_txt;
    private javax.swing.JTextField respASPT2_txt;
    private javax.swing.JTextField respTGSPT1_txt;
    private javax.swing.JTextField respTGSPT2_txt;
    private javax.swing.JButton serverMsg_button;
    private javax.swing.JButton tgsMsg_button;
    // End of variables declaration//GEN-END:variables
}
